package com.zp.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Election.proto

public final class ElectionPOJO {
  private ElectionPOJO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ElectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Election)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * int32对应java中的int型，1表示属性序号，不是值
     * </pre>
     *
     * <code>int32 term = 1;</code>
     * @return The term.
     */
    int getTerm();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>int32 type = 2;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * 消息index
     * </pre>
     *
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <pre>
     * 选举的轮次
     * </pre>
     *
     * <code>int32 ElectionId = 4;</code>
     * @return The electionId.
     */
    int getElectionId();

    /**
     * <pre>
     * 投票结果，1：通过，0：不通过
     * </pre>
     *
     * <code>int32 voteResult = 5;</code>
     * @return The voteResult.
     */
    int getVoteResult();

    /**
     * <pre>
     * 正在连接的客户端的server端口
     * </pre>
     *
     * <code>int32 port = 6;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   * protobuf使用message管理数据
   * </pre>
   *
   * Protobuf type {@code Election}
   */
  public static final class Election extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Election)
      ElectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Election.newBuilder() to construct.
    private Election(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Election() {
      content_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Election();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Election(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readInt32();
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 24: {

              index_ = input.readInt32();
              break;
            }
            case 32: {

              electionId_ = input.readInt32();
              break;
            }
            case 40: {

              voteResult_ = input.readInt32();
              break;
            }
            case 48: {

              port_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ElectionPOJO.internal_static_Election_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ElectionPOJO.internal_static_Election_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Election.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <pre>
     * int32对应java中的int型，1表示属性序号，不是值
     * </pre>
     *
     * <code>int32 term = 1;</code>
     * @return The term.
     */
    @Override
    public int getTerm() {
      return term_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>int32 type = 2;</code>
     * @return The type.
     */
    @Override
    public int getType() {
      return type_;
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;
    /**
     * <pre>
     * 消息index
     * </pre>
     *
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    @Override
    public int getIndex() {
      return index_;
    }

    public static final int ELECTIONID_FIELD_NUMBER = 4;
    private int electionId_;
    /**
     * <pre>
     * 选举的轮次
     * </pre>
     *
     * <code>int32 ElectionId = 4;</code>
     * @return The electionId.
     */
    @Override
    public int getElectionId() {
      return electionId_;
    }

    public static final int VOTERESULT_FIELD_NUMBER = 5;
    private int voteResult_;
    /**
     * <pre>
     * 投票结果，1：通过，0：不通过
     * </pre>
     *
     * <code>int32 voteResult = 5;</code>
     * @return The voteResult.
     */
    @Override
    public int getVoteResult() {
      return voteResult_;
    }

    public static final int PORT_FIELD_NUMBER = 6;
    private int port_;
    /**
     * <pre>
     * 正在连接的客户端的server端口
     * </pre>
     *
     * <code>int32 port = 6;</code>
     * @return The port.
     */
    @Override
    public int getPort() {
      return port_;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private volatile Object content_;
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 内容
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0) {
        output.writeInt32(1, term_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (index_ != 0) {
        output.writeInt32(3, index_);
      }
      if (electionId_ != 0) {
        output.writeInt32(4, electionId_);
      }
      if (voteResult_ != 0) {
        output.writeInt32(5, voteResult_);
      }
      if (port_ != 0) {
        output.writeInt32(6, port_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, index_);
      }
      if (electionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, electionId_);
      }
      if (voteResult_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, voteResult_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, port_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Election)) {
        return super.equals(obj);
      }
      Election other = (Election) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getType()
          != other.getType()) return false;
      if (getIndex()
          != other.getIndex()) return false;
      if (getElectionId()
          != other.getElectionId()) return false;
      if (getVoteResult()
          != other.getVoteResult()) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + getTerm();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + ELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getElectionId();
      hash = (37 * hash) + VOTERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getVoteResult();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Election parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Election parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Election parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Election parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Election parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Election parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Election parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Election parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Election parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Election parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Election parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Election parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Election prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * protobuf使用message管理数据
     * </pre>
     *
     * Protobuf type {@code Election}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Election)
        ElectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ElectionPOJO.internal_static_Election_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ElectionPOJO.internal_static_Election_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Election.class, Builder.class);
      }

      // Construct using ElectionPOJO.Election.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0;

        type_ = 0;

        index_ = 0;

        electionId_ = 0;

        voteResult_ = 0;

        port_ = 0;

        content_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ElectionPOJO.internal_static_Election_descriptor;
      }

      @Override
      public Election getDefaultInstanceForType() {
        return Election.getDefaultInstance();
      }

      @Override
      public Election build() {
        Election result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Election buildPartial() {
        Election result = new Election(this);
        result.term_ = term_;
        result.type_ = type_;
        result.index_ = index_;
        result.electionId_ = electionId_;
        result.voteResult_ = voteResult_;
        result.port_ = port_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Election) {
          return mergeFrom((Election)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Election other) {
        if (other == Election.getDefaultInstance()) return this;
        if (other.getTerm() != 0) {
          setTerm(other.getTerm());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getElectionId() != 0) {
          setElectionId(other.getElectionId());
        }
        if (other.getVoteResult() != 0) {
          setVoteResult(other.getVoteResult());
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Election parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Election) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int term_ ;
      /**
       * <pre>
       * int32对应java中的int型，1表示属性序号，不是值
       * </pre>
       *
       * <code>int32 term = 1;</code>
       * @return The term.
       */
      @Override
      public int getTerm() {
        return term_;
      }
      /**
       * <pre>
       * int32对应java中的int型，1表示属性序号，不是值
       * </pre>
       *
       * <code>int32 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(int value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * int32对应java中的int型，1表示属性序号，不是值
       * </pre>
       *
       * <code>int32 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 type = 2;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <pre>
       * 消息index
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @return The index.
       */
      @Override
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       * 消息index
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息index
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int electionId_ ;
      /**
       * <pre>
       * 选举的轮次
       * </pre>
       *
       * <code>int32 ElectionId = 4;</code>
       * @return The electionId.
       */
      @Override
      public int getElectionId() {
        return electionId_;
      }
      /**
       * <pre>
       * 选举的轮次
       * </pre>
       *
       * <code>int32 ElectionId = 4;</code>
       * @param value The electionId to set.
       * @return This builder for chaining.
       */
      public Builder setElectionId(int value) {
        
        electionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 选举的轮次
       * </pre>
       *
       * <code>int32 ElectionId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearElectionId() {
        
        electionId_ = 0;
        onChanged();
        return this;
      }

      private int voteResult_ ;
      /**
       * <pre>
       * 投票结果，1：通过，0：不通过
       * </pre>
       *
       * <code>int32 voteResult = 5;</code>
       * @return The voteResult.
       */
      @Override
      public int getVoteResult() {
        return voteResult_;
      }
      /**
       * <pre>
       * 投票结果，1：通过，0：不通过
       * </pre>
       *
       * <code>int32 voteResult = 5;</code>
       * @param value The voteResult to set.
       * @return This builder for chaining.
       */
      public Builder setVoteResult(int value) {
        
        voteResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 投票结果，1：通过，0：不通过
       * </pre>
       *
       * <code>int32 voteResult = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteResult() {
        
        voteResult_ = 0;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       * 正在连接的客户端的server端口
       * </pre>
       *
       * <code>int32 port = 6;</code>
       * @return The port.
       */
      @Override
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       * 正在连接的客户端的server端口
       * </pre>
       *
       * <code>int32 port = 6;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 正在连接的客户端的server端口
       * </pre>
       *
       * <code>int32 port = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Election)
    }

    // @@protoc_insertion_point(class_scope:Election)
    private static final Election DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Election();
    }

    public static Election getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Election>
        PARSER = new com.google.protobuf.AbstractParser<Election>() {
      @Override
      public Election parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Election(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Election> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Election> getParserForType() {
      return PARSER;
    }

    @Override
    public Election getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Election_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Election_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Election.proto\"|\n\010Election\022\014\n\004term\030\001 \001" +
      "(\005\022\014\n\004type\030\002 \001(\005\022\r\n\005index\030\003 \001(\005\022\022\n\nElect" +
      "ionId\030\004 \001(\005\022\022\n\nvoteResult\030\005 \001(\005\022\014\n\004port\030" +
      "\006 \001(\005\022\017\n\007content\030\007 \001(\tB\016B\014ElectionPOJOb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Election_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Election_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Election_descriptor,
        new String[] { "Term", "Type", "Index", "ElectionId", "VoteResult", "Port", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
